env:
  browser: true
  es2021: true
extends:
  - airbnb-base
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules: {
  'no-console': 'off',
  'import/extensions': ['error', 'ignorePackages', {
    js: 'never',
  }],
  'no-await-in-loop': 'off',
}
